@hostname = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{hostname}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe1@example.com",
  "password": "123456"
}

###

# @name authenticate
POST {{hostname}}/sessions
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "123456"
}

###

# @name create_question
POST {{hostname}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "What is NestJS?",
  "content": "NestJS is a progressive Node.js framework for building efficient, reliable and scalable server-side applications."
}

###

# @name fetch_recent_questions
GET {{hostname}}/questions/recent
Content-Type: application/json
Authorization: Bearer {{authToken}}
